apiVersion: 3
dataDisplay:
  textFormat: text-orig-full
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: ' '
  sectionSep2: ':'
docs:
  docPage: about
  featureBase: https://github.com/CenterBLC/N1904/blob/main/docs/features/<feature>.md
  featurePage: README
  docRoot: https://github.com/CenterBLC/N1904
  docBase: https://github.com/CenterBLC/N1904/tree/main/docs
interfaceDefaults:
  fmt: text-orig-full
provenanceSpec:
  corpus: Nestle 1904 Greek New Testament
  doi: 10.5281/zenodo.13117910
  moduleSpecs: []
  version: 1.0.0
  webBase: https://learner.bible/text/show_text/nestle1904/
  webHint: Show this on the website
  webLang: en
  webUrl: https://learner.bible/text/show_text/nestle1904/<1>/<2>/<3>
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
  branch: main
  org: CenterBLC
  repro: N1904
typeDisplay:
  clause:
    label: '{typ} {function} {rela} \\ {cls} {role} {junction}'
    style: ''
    condense: true
  group:
    label: '{typ} {function} {rela} \\ {typems} {role} {rule}'
    style: ''
  phrase:
    label: '{typ} {function} {rela} \\ {typems} {role} {rule}'
    style: ''
    condense: true
  sentence:
    label: '{typ} {function} {rela} \\ {role} {rule}'
    style: ''
  subphrase:
    label: '{typ} {function} {rela} \\ {typems} {role} {rule}'
    style: ''
  verse:
    label: '{book} {chapter}:{verse}'
    style: ''
    condense: true
  wg:
    label: '{typems} {role} {rule} {junction}'
    style: ''
    condense: true
  word:
    featuresBare:
    - gloss
    features:
    - lemma
    - sp
    - morph
writing: grc
