remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap

title: Nestle 1904 GNT
description: Text-Fabric dataset for Greek New Testament based upon Nestle 1904
show_downloads: false
