remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap

title: N1904-TF
description: Text-Fabric dataset of the Greek New Testament, based on the Nestle 1904 (7th printing) edition.
show_downloads: false
